service:
  name: discord-lambda
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev

package:
  individually: true

functions:
  cron:
    handler: src/handler.postMessage
    events:
      - schedule: cron(0 23 * * ? *)
  youtube:
    handler: src/handler.youtubePlaylistChecker
    events:
      - schedule: cron(0 23 * * ? *)